name: ci-golang-workflow
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.23.2
      - name: Run tests
        run: go test
        working-directory: src
      - name: Run application
        run: go run math.go
        working-directory: src
